config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  authenticated :admin do
    root 'admin/mail_users#index', as: :authenticated_root
  end

  root "home#login"

  namespace :api do
    resources :mail_users, only: [:create]
  end

  namespace :admin do
    root to: redirect('/admin/mail_users')
    resources :mail_users, only: [:index]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mail_user.rb
class MailUser < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :nationality, presence: true

    before_save :downcase_params, :strip_params

    private 
    def downcase_params
      self.nationality.downcase!
      self.email.downcase!
    end

    def strip_params
        self.nationality.strip!
        self.email.downcase!
    end
end

app/models/status.rb
class Status
    OK = {"status": "Ok"}
end

app/controllers/admin/mail_users_controller.rb
class Admin::MailUsersController < ApplicationController
    before_action :authenticate_admin!

    def index
      if params[:nationality].present?
        @mail_users = MailUser.order(created_at: :desc).where(nationality: params[:nationality])
      else
        @mail_users = MailUser.order(created_at: :desc)
      end
    end
end

app/controllers/api/mail_users_controller.rb
module Api
  class MailUsersController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      @mail_user = MailUser.new(mail_user_params)
      
      if @mail_user.save
        render json: Status::OK, :status => :created
      else
        render json: { 'errors' => @mail_user.errors }, :status => :bad_request
      end

    end

    private
    def mail_user_params
      params.require(:mail_user).permit(:email, :nationality)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/mail_users/index.html.erb
<div class="row">
  <div class="col-9">
    <h1>Usuários Cadastrados (<%= @mail_users.count %>)</h1>    
  </div>
  <div class="col-3">
    <div style="float: none; height: 100%">
      <%= link_to 'Ver todos', admin_mail_users_url if params[:nationality].present? %>
    </span>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>País</th>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <% @mail_users.each do |mail_user| %>
      <tr>
        <td><%= mail_user.email %></td>
        <td><%= link_to mail_user.nationality, admin_mail_users_url(:nationality => mail_user.nationality ) %></td>
        <td><%= mail_user.created_at.strftime("%d/%m") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Calculadora de Poupança</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="alert alert-primary" role="alert" style="display: <%= notice.blank? ? 'none' : 'block'  %>"><%= notice %></div>
          <div class="alert alert-danger" role="alert" style="display: <%= alert.blank? ? 'none' : 'block'  %>"><%= alert %></div>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>